config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :categories do
    resources :subcategories
  end

  resources :subcategories do
    resources :products
  end
  resources :buy_product

  delete "/cart", to: "buy_product#empty_cart", as: "empty_cart"

  get "/update_shipping", to: "buy_product#update_shipping"
   resources :prime_subscriptions, only: [ :create ]
   get "prime_subscriptions/success", to: "prime_subscriptions#success"

   resources :product_payments, only: [ :create ]
  get "product_payments/success", to: "product_payments#success"

  resource :profile, only: [ :edit, :update ]

  resource :email, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]

  resources :purchases, only: [ :index ]

  resources :purchases, only: [ :index ] do
    resources :reviews, only: [ :new, :create ]
  end

  namespace :owner do
    resources :products do
      member do
        patch "update_sizes"
        patch "update_styles"
        patch "add_images"
        delete "remove_image"
      end
    end
    resources :purchases, only: :index
  end
  get "/products/:id/get_image", to: "products#get_image"
  resources :orders
  # Route to show the most recent order
  get "orders/most_recent", to: "orders#most_recent", as: :most_recent_order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory
  has_rich_text :description
  has_many_attached :images
  has_many :reviews, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :purchased_users, through: :purchases, source: :user, dependent: :destroy
  scope :from_same_company, ->(company_name, product_id) { where(company_name: company_name).where.not(id: product_id) }
  #  has_many :sizes
  #  has_many :styles
  has_many :product_sizes, dependent: :destroy
  has_many :sizes, through: :product_sizes

  has_many :product_styles, dependent: :destroy
  has_many :styles, through: :product_styles

  has_many :product_payments, through: :purchases, dependent: :destroy
  validates :headline, presence: true
  validates :company_name, presence: true
  validates :description, presence: true
  monetize :price_cents, allow_nil: true
  validates :country_code, presence: true

   def update_average_rating
  average_rating = reviews.average(:final_rating)
  update_column(:average_final_rating, average_rating)
   end

def average_fivestar_rating
  reviews.average(:fivestar_rating)
end

def average_fourstar_rating
  reviews.average(:fourstar_rating)
end

def average_threestar_rating
  reviews.average(:threestar_rating)
end

def average_twostar_rating
  reviews.average(:twostar_rating)
end

def average_onestar_rating
  reviews.average(:onestar_rating)
end

# ###########################Percentage#######################
def review_percentages
  star_counts = {
    5 => reviews.sum(:fivestar_rating),
    4 => reviews.sum(:fourstar_rating),
    3 => reviews.sum(:threestar_rating),
    2 => reviews.sum(:twostar_rating),
    1 => reviews.sum(:onestar_rating)
  }

  total_ratings = star_counts.values.sum.to_f

  return { 5 => 0, 4 => 0, 3 => 0, 2 => 0, 1 => 0 } if total_ratings.zero?

  star_counts.transform_values { |count| ((count / total_ratings) * 100).round }
end

def discount_percentage
  return 0 unless discount_price.present? && price.present? && price.cents > 0

  discount = ((price.to_f - discount_price.to_f) / price.to_f) * 100
  discount.round(2) # Rounds to 2 decimal places
end
end

app/controllers/owner/products_controller.rb
module Owner
  class ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product, only: [ :edit, :update, :add_images, :remove_image, :destroy ]

    def new
      @product = Product.new
    end

    def create
      @product = current_user.products.create!(product_params)

      redirect_to edit_owner_product_path(@product), notice: "product added successfully"
    end

    def index
      @products = current_user.products.order(created_at: :desc)
    end

    def update
      if @product.update!(product_params)
        redirect_to edit_owner_product_path, notice: "product updated successfully"
      else
        redirect_back fallback_location: edit_owner_product_path, alert: "Failed to update product"
      end
    end

    def update_sizes
      set_product
      if @product.update(size_ids: params[:product][:size_ids])
        redirect_to edit_owner_product_path(@product), notice: "Sizes updated successfully"
      else
        redirect_back fallback_location: edit_owner_product_path(@product), alert: "Failed to update sizes"
      end
    end

    def update_styles
      set_product
      if @product.update(style_ids: params[:product][:style_ids])
        redirect_to edit_owner_product_path(@product), notice: "Styles updated successfully"
      else
        redirect_back fallback_location: edit_owner_product_path(@product), alert: "Failed to update styles"
      end
    end



    def add_images
      # TODO: Possibly optimise this if no images are selected.
      @product.images.attach(params[:product][:images])
      redirect_to edit_owner_product_path, notice: "product images uploaded"
    end

    def remove_image
      image = @product.images.find(params[:image_id])
      if image.destroy!
        redirect_to edit_owner_product_path, notice: "Image removed successfully"
      else
        redirect_back fallback_location: edit_owner_product_path, alert: "Failed to remove image"
      end
    end


    def destroy
      @product.destroy
      redirect_to owner_products_path, alert: "#{@product.name} deleted successfully."
    end

    private

    def set_product
      @product = current_user.products.find(params[:id])
      @size = @product.sizes.first # Assign the first size of the product
      @style = @product.styles.first # Assign the first style of the product
    end

    def sizes_params
      params.require(:product).permit(size_ids: [])
    end

    def styles_params
      params.require(:product).permit(style_ids: [])
    end


    def product_params
      params.require(:product).permit(
        :headline,
        :price,
        :description,
        :country_code
      )
    end
  end
end

app/controllers/owner/purchases_controller.rb
module Owner
  class PurchasesController < ApplicationController
    before_action :authenticate_user!
    # TODO: Order- show latest first, same for other apis
    def index
      @purchases = current_user.products.map(&:purchases).flatten
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @subcategory = Subcategory.find(params[:subcategory_id])  # Get the specific subcategory
    @products = @subcategory.products.includes(:reviews)  # Fetch products of this subcategory # Subcategory.first.products

    @products.each do |product|
      product.instance_variable_set(:@review_percentages, product.review_percentages)
    end
    # Debugging logs
    # Rails.logger.debug "Min Price: #{params[:min_price]}"
    # Rails.logger.debug "Max Price: #{params[:max_price]}"
    # Price filtering logic 
    if params[:min_price].present? && params[:max_price].present?
      min_price = params[:min_price].to_f
      max_price = params[:max_price].to_f
      # Ensure min_price and max_price are numeric and the query can handle the price range
      @products = @products.where(price: min_price..max_price)
    end

    respond_to do |format|
      format.html # Regular page load
      format.json { render json: @products } # JSON response if needed
      format.turbo_stream { render turbo_stream: turbo_stream.replace("product_list", template: "products/index") }
    end
  end

  def show
    @product = Product.includes(:reviews).find(params[:id])
    # showing all poducts below
    @subcategory = Subcategory.find(params[:subcategory_id])  # Get the specific subcategory
    @products = @subcategory.products.includes(:reviews)  # Fetch products of this subcategory # Subcategory.first.products
    @related_products = Product.from_same_company(@product.company_name, @product.id)
    @sizes = Size.all
    @styles = Style.all
    @size = @product.sizes.first|| Size.new(name: "Default") # Default to the first size
    @style = @product.styles.first|| Style.new(name: "Default") # Default to the first size
    @tomorrow_date = (Date.today + 3).strftime("%A, %B %d") # Example: "Thursday, March 16"
    # raise
  end
  def get_image
    product = Product.find(params[:id])
    image_name = params[:image_name]

    # Find the correct image in Active Storage
    image = product.images.find { |img| img.filename.to_s == image_name }

    if image
      render json: { image_url: url_for(image) }
    else
      render json: { error: "Image not found" }, status: :not_found
    end
  end
end

app/views/owner/products/_edit_size_item.html.erb
<div class="sizes">
     
    
      <div class="flex space-x-4">
    
      <span class="size-name"><%= size.name %></span>
    </div>

</div>

app/views/owner/products/_edit_style_item.html.erb
<div class="styles">
     
    
      <div class="flex space-x-4">
    
      <span class="style-name"><%= style.name %></span>
    </div>

</div>

app/views/owner/products/_form.html.erb
<div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
  <div>
    <h2 class="text-base font-semibold leading-7 text-gray-900">product Information</h2>

    <%= form_with model: @product, url: path, class:'mt-6 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6' do |f| %>
    <div class="flex space-x-4">
      
      <div class="sm:col-span-3" style="padding-left:5px;">
        <%= f.label :price, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :price, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      </div>
      <div class="col-span-full">
        <%= f.label :headline, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :headline, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="col-span-full">
        <%= f.label :description, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.rich_text_area :description, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>

      <div class="flex space-x-4">
       
      <!-----flex space-x-4 div end-------->
    </div>

     <div class="flex space-x-4">

      <div class="sm:col-span-2"  style="padding-left:5px;"> 
        <%= f.label :country, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.country_select :country_code, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      </div>
      <div class="col-span-full">
        <%= f.submit "Save", class:"save-btn cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary " %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/owner/products/edit.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>
  
  <main>
    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
   <h2 class="text-base font-semibold leading-7 text-gray-900">Product Images</h2>
<div class="mt-2 flex flex-wrap gap-2">
  <% @product.images.each do |image| %>
    <div class="relative w-40 h-40">
      <%= image_tag image, class: 'w-40 h-40 object-cover rounded-md' %>
      <div class="text-center mt-1">
        <%= button_to remove_image_owner_product_path(image_id: image.id), method: :delete, class: "save-btn text-sm text-red-600 font-semibold hover:underline" do %>
          Remove
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= form_with model: @product, url: add_images_owner_product_path, multipart: true, class:'mt-6' do |f| %>
  <div>
    <div>
      <%= f.label 'Add Images', class:'block text-base font-semibold leading-7 text-gray-900 mb-2' %>
      <%= f.file_field :images, multiple: true, class:'font-medium' %>
    </div>

    <%= f.submit "Upload Images", class:"save-btn cursor-pointer mt-2 flex items-center justify-center rounded-md" %>
  </div>
<% end %>


    <%= render 'owner/products/form', path: owner_product_path %>

   
    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Sizes</h2>
<%= form_with model: @product, url: update_sizes_owner_product_path, method: :patch, class: 'mt-6' do |f| %>
  <div class="mt-6 grid grid-cols-1 md:grid-cols-2">
    <% Size.all.each do |size| %>
      <div class="flex items-center gap-2">
        <%= f.check_box :size_ids, { multiple: true, checked: @product.sizes.include?(size) }, size.id, nil %>
        <%= render 'owner/products/edit_size_item', size: size %>
      </div>
    <% end %>
  </div>
  <div class="col-span-full">
    <%= f.submit "Save", class:"save-btn cursor-pointer mt-2 flex items-center justify-center rounded-md " %>
  </div>
<% end %>
      </div>
    </div>

    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Styles</h2>

     <%= form_with model: @product, url: update_styles_owner_product_path, method: :patch, class: 'mt-6' do |f| %>
  <div class="mt-6 grid grid-cols-1 md:grid-cols-2">
    <% Style.all.each do |style| %>
      <div class="flex items-center gap-2">
        <%= f.check_box :style_ids, { multiple: true, checked: @product.styles.include?(style) }, style.id, nil %>
        <%= render 'owner/products/edit_style_item', style: style %>
      </div>
    <% end %>
  </div>
  <div class="col-span-full">
    <%= f.submit "Save", class:"save-btn cursor-pointer mt-2 flex items-center justify-center rounded-md " %>
  </div>
<% end %>
      </div>
    </div>

    <div class="px-8 py-8 border border-red-500 rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-2xl font-semibold leading-7 text-red-500">Delete product</h2>
        <p class="my-2">This action is permanent and irreversible. Are you sure?</p>
         <%= button_to 'Delete', owner_product_path, method: :delete, class:"delete-btn mt-4 rounded p-1 bg-red-500 hover:bg-red-700 text-white px-8 py-2" %>
      </div>
    </div>
  </main>
</div>

app/views/owner/products/index.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>
  
  <main class="px-8 my-8 lg:flex-auto">
    <div>
      <div class="flex justify-between items-center">
        <h2 class="text-2xl font-semibold leading-7 text-gray-900">products</h2>
        <%= link_to 'Add product', new_owner_product_path, class:'cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary ' %>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:gap-x-8">
        <% @products.each do |product| %>
          <div class="flex flex-col">
            <%= render 'products/product_item', product: product, minimal_details: false %>
            <%= link_to 'Edit', edit_owner_product_path(product), class:'cursor-pointer mt-2 flex items-center justify-center rounded-md border border-primary text-primary px-8 py-2 text-base font-medium hover:text-white hover:bg-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2' %>
          </div>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/owner/products/new.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>
  
  <main>
    <%= render 'owner/products/form', path: owner_products_path %>
  </main>
</div>