config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :categories do
    resources :subcategories
  end

  resources :subcategories do
    resources :products
  end
  resources :buy_product

  delete "/cart", to: "buy_product#empty_cart", as: "empty_cart"

  get "/update_shipping", to: "buy_product#update_shipping"
   resources :prime_subscriptions, only: [ :create ]
   get "prime_subscriptions/success", to: "prime_subscriptions#success"

   resources :product_payments, only: [ :create ]
  get "product_payments/success", to: "product_payments#success"

  resource :profile, only: [ :edit, :update ]

  resource :email, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]

  resources :purchases, only: [ :index ]

  resources :purchases, only: [ :index ] do
    resources :reviews, only: [ :new, :create ]
  end

  namespace :owner do
    resources :products do
      member do
        patch "update_sizes"
        patch "update_styles"
        patch "add_images"
        delete "remove_image"
      end
    end
    resources :purchases, only: :index
  end
  get "/products/:id/get_image", to: "products#get_image"
  resources :orders
  # Route to show the most recent order
  get "orders/most_recent", to: "orders#most_recent", as: :most_recent_order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory
  has_rich_text :description
  has_many_attached :images
  has_many :reviews, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :purchased_users, through: :purchases, source: :user, dependent: :destroy
  scope :from_same_company, ->(company_name, product_id) { where(company_name: company_name).where.not(id: product_id) }
  #  has_many :sizes
  #  has_many :styles
  has_many :product_sizes, dependent: :destroy
  has_many :sizes, through: :product_sizes

  has_many :product_styles, dependent: :destroy
  has_many :styles, through: :product_styles

  has_many :product_payments, through: :purchases, dependent: :destroy
  validates :headline, presence: true
  validates :company_name, presence: true
  validates :description, presence: true
  monetize :price_cents, allow_nil: true
  validates :country_code, presence: true

   def update_average_rating
  average_rating = reviews.average(:final_rating)
  update_column(:average_final_rating, average_rating)
   end

def average_fivestar_rating
  reviews.average(:fivestar_rating)
end

def average_fourstar_rating
  reviews.average(:fourstar_rating)
end

def average_threestar_rating
  reviews.average(:threestar_rating)
end

def average_twostar_rating
  reviews.average(:twostar_rating)
end

def average_onestar_rating
  reviews.average(:onestar_rating)
end

# ###########################Percentage#######################
def review_percentages
  star_counts = {
    5 => reviews.sum(:fivestar_rating),
    4 => reviews.sum(:fourstar_rating),
    3 => reviews.sum(:threestar_rating),
    2 => reviews.sum(:twostar_rating),
    1 => reviews.sum(:onestar_rating)
  }

  total_ratings = star_counts.values.sum.to_f

  return { 5 => 0, 4 => 0, 3 => 0, 2 => 0, 1 => 0 } if total_ratings.zero?

  star_counts.transform_values { |count| ((count / total_ratings) * 100).round }
end

def discount_percentage
  return 0 unless discount_price.present? && price.present? && price.cents > 0

  discount = ((price.to_f - discount_price.to_f) / price.to_f) * 100
  discount.round(2) # Rounds to 2 decimal places
end
end

app/controllers/owner/products_controller.rb
module Owner
  class ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product, only: [ :edit, :update, :add_images, :remove_image, :destroy ]

    def new
      @product = Product.new
    end

    def create
      @product = current_user.products.create!(product_params)

      redirect_to edit_owner_product_path(@product), notice: "product added successfully"
    end

    def index
      @products = current_user.products.order(created_at: :desc)
    end

    def update
      if @product.update!(product_params)
        redirect_to edit_owner_product_path, notice: "product updated successfully"
      else
        redirect_back fallback_location: edit_owner_product_path, alert: "Failed to update product"
      end
    end

    def update_sizes
      set_product
      if @product.update(size_ids: params[:product][:size_ids])
        redirect_to edit_owner_product_path(@product), notice: "Sizes updated successfully"
      else
        redirect_back fallback_location: edit_owner_product_path(@product), alert: "Failed to update sizes"
      end
    end

    def update_styles
      set_product
      if @product.update(style_ids: params[:product][:style_ids])
        redirect_to edit_owner_product_path(@product), notice: "Styles updated successfully"
      else
        redirect_back fallback_location: edit_owner_product_path(@product), alert: "Failed to update styles"
      end
    end



    def add_images
      # TODO: Possibly optimise this if no images are selected.
      @product.images.attach(params[:product][:images])
      redirect_to edit_owner_product_path, notice: "product images uploaded"
    end

    def remove_image
      image = @product.images.find(params[:image_id])
      if image.destroy!
        redirect_to edit_owner_product_path, notice: "Image removed successfully"
      else
        redirect_back fallback_location: edit_owner_product_path, alert: "Failed to remove image"
      end
    end


    def destroy
      @product.destroy
      redirect_to owner_products_path, alert: "#{@product.name} deleted successfully."
    end

    private

    def set_product
      @product = current_user.products.find(params[:id])
      @size = @product.sizes.first # Assign the first size of the product
      @style = @product.styles.first # Assign the first style of the product
    end

    def sizes_params
      params.require(:product).permit(size_ids: [])
    end

    def styles_params
      params.require(:product).permit(style_ids: [])
    end


    def product_params
      params.require(:product).permit(
        :headline,
        :price,
        :description,
        :country_code
      )
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @subcategory = Subcategory.find(params[:subcategory_id])  # Get the specific subcategory
    @products = @subcategory.products.includes(:reviews)  # Fetch products of this subcategory # Subcategory.first.products

    @products.each do |product|
      product.instance_variable_set(:@review_percentages, product.review_percentages)
    end
    # Debugging logs
    # Rails.logger.debug "Min Price: #{params[:min_price]}"
    # Rails.logger.debug "Max Price: #{params[:max_price]}"
    # Price filtering logic 
    if params[:min_price].present? && params[:max_price].present?
      min_price = params[:min_price].to_f
      max_price = params[:max_price].to_f
      # Ensure min_price and max_price are numeric and the query can handle the price range
      @products = @products.where(price: min_price..max_price)
    end

    respond_to do |format|
      format.html # Regular page load
      format.json { render json: @products } # JSON response if needed
      format.turbo_stream { render turbo_stream: turbo_stream.replace("product_list", template: "products/index") }
    end
  end

  def show
    @product = Product.includes(:reviews).find(params[:id])
    # showing all poducts below
    @subcategory = Subcategory.find(params[:subcategory_id])  # Get the specific subcategory
    @products = @subcategory.products.includes(:reviews)  # Fetch products of this subcategory # Subcategory.first.products
    @related_products = Product.from_same_company(@product.company_name, @product.id)
    @sizes = Size.all
    @styles = Style.all
    @size = @product.sizes.first|| Size.new(name: "Default") # Default to the first size
    @style = @product.styles.first|| Style.new(name: "Default") # Default to the first size
    @tomorrow_date = (Date.today + 3).strftime("%A, %B %d") # Example: "Thursday, March 16"
    # raise
  end
  def get_image
    product = Product.find(params[:id])
    image_name = params[:image_name]

    # Find the correct image in Active Storage
    image = product.images.find { |img| img.filename.to_s == image_name }

    if image
      render json: { image_url: url_for(image) }
    else
      render json: { error: "Image not found" }, status: :not_found
    end
  end
end

app/views/products/_buy_product.html.erb
<div id="product-details" data-product-id="<%= @product.id %>" data-base-price="<%= @product.price %>">
  <div class="flex justify-between ...">
    <h3>Buy new:</h3>
    
<% if current_user&.prime_member.nil? || current_user&.prime_member == false %>
   <div class="mt-8 border-t border-gray-300 pt-12" data-turbo="false"> 
  <%= form_with url: prime_subscriptions_path, method: :post do |form| %>
    <%= form.submit "Subscribe to Prime",
     class: "btn btn-primary" %>
  <% end %>
  
</div>
<% end %>
    </div>
  <p class="flex font-semibold text-lg text-black"><span id="product-price"><%= @product.price %></span></p>
  <p class="flex"><span id="total-price"><%= @product.price %></span></span>&nbsp; Shipping & Import Charges to&nbsp;
  <span class="delivery_location"><%= "Select a Country" %></span>&nbsp;
 <button  class="flex items-center gap-1"
  data-controller="shipping"
  data-action="click->shipping#toggleShippingModal">
  Details
  <svg xmlns="http://www.w3.org/2000/svg"
       fill="none"
       viewBox="0 0 24 24"
       stroke-width="1.5" 
       stroke="currentColor"
       class="size-4 text-black">
    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
  </svg>
</button>

  </p>
  <p class="flex text-black">Delivery <span class="font-bold text-black" id="estimated-delivery"><%= @tomorrow_date %></span> Order within  <span class="font-semibold">23 hrs 54 mins</span></p>
 <button
  class="flex items-center gap-1"
  data-controller="delivery"
  data-action="click->delivery#toggleDeliveryModal"
>
  <span class="flex items-center">
    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      viewBox="0 0 24 24" 
      fill="currentColor" 
      width="12" 
      height="12">
      <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5S10.62 6.5 12 6.5s2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/>
    </svg>
    Deliver to &nbsp;<span class="delivery_location"><%= "Select a Country" %></span>

  </span>
</button>

<!-- Shipping Cost and Total Price -->
 <%# <p>Shipping Cost: $<span id="shipping-cost">0</span></p>  %>
<%# <p>Total Price: $<span id="total-price"><%= @product.price ></span></p> %>
<div>
  <label for="quantity">Quantity:</label>
  <select id="quantity" name="quantity">
    <% (1..10).each do |q| %>
      <option value="<%= q %>"><%= q %></option>
    <% end %>
  </select>
     <% if current_user&.prime_eligible? %>
  <p>Prime User enjoy free shipping </p>
<% end %>
</div>

 

<div>
 <label for="shipping-method">Shipping Method:</label>
<select id="shipping-method" name="shipping-method" data-action="change->delivery#updateTotalPrice">
  <option value="standard">Standard</option>
  <option value="expedited">Expedited</option>
  <option value="same_day">Same-Day</option>
</select>
</div>

<button
  data-controller="delivery"
  data-buy-product-url="<%= update_shipping_path %>"
  data-product-id="<%= @product.id %>"
  data-style="<%= @style&.name %>"
  data-size="<%= @size&.name %>"
  type="button"
  data-action="click->delivery#buyProduct"
  data-delivery-target="cartButton"
  class="reserve-btn hidden">
  Add to Cart
</button>




  <%= render 'shared/modal', modalTriggerId: "delivery", content: 'products/delivery_modal', content_params: {product: @product} %>
   <%= render 'shared/modal', modalTriggerId: "shipping", content: 'products/shipping_modal', content_params: {product: @product} %>
</div>

  

app/views/products/_delivery_modal.html.erb
   <div class="grid ">
    <!-- Review Stats -->
    <section aria-labelledby="delivery-stats" class="col-span-2 pt-10 pb-10">
     
    <button data-action="click->modal#toggleModal" type="button" class="relative rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
    <span class="absolute -inset-2.5"></span>
    <span class="sr-only">Close panel</span>
    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  </button>
    <!-- Header -->
    <div class="flex justify-between items-center">
      <h2 class="text-lg font-semibold">Choose your location</h2>
      
    </div>

    

    <!-- Sign-in Button -->
     <% if user_signed_in? %>
           <!-- Description -->
    <p class="text-sm text-gray-600 mt-2">
      Delivery options and delivery speeds may vary for different locations
    </p>
        <% else %>
        <!-- Description -->
    <p class="text-sm text-gray-600 mt-2">
      Sign in before selecting location of delivery
    </p>
            <%= link_to "Sign in", new_user_session_path, class: "block w-full bg-yellow-500 text-black font-bold py-2 rounded-md", role: "menuitem", tabindex: "-1" %>
            <p class="text-xs mt-1">New customer? <%= link_to "Start here.", new_user_registration_path, class: "text-blue-600" %></p>
        <% end %>
<!-- Delivery Location Modal -->
<div data-controller="delivery"> 
  <div class="mt-4 text-center text-gray-500">or enter a US zip code</div>

  <div class="mt-2 flex">
   <input id="zip-code-input" type="text" placeholder="Enter zip code"
  class="border p-2 w-full rounded-l-md focus:ring focus:ring-yellow-300"
  data-action="input->delivery#updateCountryByZip"
  data-delivery-target="zipInput">  <!-- ✅ This must exist! -->

        
    <button id="apply-zip-button" 
      class="bg-gray-200 px-4 rounded-r-md hover:bg-gray-300" 
      data-action="click->delivery#updateCountryByZip">Apply</button>
  </div>



 <%= form_with url: subcategory_product_path(@product.subcategory, @product), method: :post, local: false do |f| %>
  <!-- Country Selection -->
  <div class="mt-4 text-center text-gray-500">or ship outside the US</div>
  <%= f.country_select :country, { default: 'US' }, { class: 'border p-2 w-full rounded-md mt-2',
   data: { delivery_target: "countrySelect", action: "change->delivery#updateDeliveryLocation"} } %>
<% end %>
  </div>

    <!-- Done Button -->
    <button data-action="click->modal#toggleModal"
    class="bg-yellow-400 w-full py-2 mt-4 font-semibold rounded-md hover:bg-yellow-500">
      Done
    </button>
  </div>
</div>
</section>
</div>

app/views/products/_horizontal_product_review.html.erb
<!-- Star Rating & Reviews Count -->
<div class=" items-center mt-2">
  <!-- Stars -->
  <div class=" text-yellow-500">
    <% if product.average_final_rating.present? %>
              <% full_stars = product.average_final_rating.floor %>
              <% half_star = (product.average_final_rating.round(2) % 1) >= 0.5 %>
              <% empty_stars = 5 - full_stars - (half_star ? 1 : 0) %>
              <% full_stars.times { %><span>&#9733;</span><% } %>
              <% if half_star %><span>&#9733;&#xFE0E;</span><% end %>
              <% empty_stars.times { %><span class="text-gray-300">&#9733;</span><% } %>
              <%end%>
  </div>

  <!-- Reviews Count (Clickable) -->
  <span class="text-black-600 text-sm ml-2">
    <%= number_with_delimiter(product.reviews_count) %>
  </span>
</div>

<!-- Reviews Modal Trigger -->
<% if product.reviews_count > 0 %>
  <%= render 'shared/modal',
    modalTriggerId: "reviews_#{product.id}", # Unique ID for each product
    content: 'products/reviews_modal', 
    content_params: { product: product }
  %>
<% end %>

app/views/products/_mini_product_item.html.erb
<div class="flex items-center">
  <% if product.images.present? %>
    <%= image_tag product.images[0], class:"w-24 h-24 object-cover rounded-md"%>
  <% end %>
  <div class="ml-3 text-black font-medium">
    <div class=><%= product.headline %></div>
    <span class="inline-flex items-center pointer-events-none block text-sm text-black mt-2">
      <svg class="mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true" role="presentation" focusable="false" style="display: block; height: 12px; width: 12px; fill: currentcolor;">
        <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
      </svg>
      <% if product.reviews_count > 0 %>
        <%= product.average_final_rating.round(2) %> (<%= product.reviews_count %> reviews)
      <% else %>
        New
      <% end %>
    </span>
  </div>
</div>

app/views/products/_product_item.html.erb
<%= link_to subcategory_product_path(product.subcategory, product) do%>
  <div class="group relative cursor-pointer " >
    <div class="relative overflow-hidden rounded-md bg-gray-200">

     <div class="swiper"  style="height:250px;">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
          <% product.images.each do |image| %>
             <%= image_tag image, id: "product-image", class:'swiper-slide',
                  style: "cursor: pointer;  border-radius: 8px;"%>
          <% end %>
        </div>
        
        <%# TODO: Swiper buttons are not working %>
        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
      </div>

        </div>

        <div class="mt-2">
      <div class="flex justify-between">
        <h3 class="text-base font-medium text-gray-700 line-clamp-1">
           <%= country_name(product.country_code) %>
        </h3>
        <p class="flex items-center text-sm font-light">
          <svg
            class="mr-1 block w-3 h-3 fill-current"
            xmlns="http://www.w3.org/2000/svg" 
            viewBox="0 0 32 32" 
            aria-hidden="true" 
            role="presentation" 
            focusable="false" 
            style="width: 15px;"
          >
            <path fill-rule="evenodd" d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z"></path>
          </svg>
          <% if product.reviews_count > 0 %>
            <%= product.average_final_rating.round(2) %> (<%= product.reviews_count %>)
          <% else %>
            New
          <% end %>
        </p>
      </div>


        <% if minimal_details %>
        <p class="mt-0.5 text-sm text-gray-500"><%= product.size.first %></p>
        <p class="mt-0.5 text-sm text-gray-500"><%= product.style.first %></p>
      <% else %>
        <p class="mt-0.5 text-sm text-gray-500"><%= product.color %></p>
        <p class="mt-0.5 text-sm text-gray-500"><%= product.ear_placement %></p>
        <p class="mt-0.5 text-sm text-gray-500"><%= product.form_factor %></p>
        <p class="mt-0.5 text-sm text-gray-500"><%= product.impedance %></p>
        <p class="mt-0.5 text-sm font-light text-black">
          <span class="font-medium"><%= humanized_money_with_symbol(product.price) %></span>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/_review_detail.html.erb
<div class="flex items-center mt-10 space-x-1">
  <%#= review.final_rating.round(0) %>
  <% 5.times do |i| %>
    <svg class="<%= review.final_rating.round(0) > i ? 'star-selected' : 'text-gray-400' %>"
      xmlns="http://www.w3.org/2000/svg" 
      viewBox="0 0 32 32" 
      aria-hidden="true" 
      role="presentation" 
      focusable="false" 
      class=" fill-current" style="width:10px;">
      <path fill-rule="evenodd" 
        d="m15.1 1.58-4.13 8.88-9.86 1.27a1 1 0 0 0-.54 1.74l7.3 6.57-1.97 9.85a1 1 0 0 0 1.48 1.06l8.62-5 8.63 5a1 1 0 0 0 1.48-1.06l-1.97-9.85 7.3-6.57a1 1 0 0 0-.55-1.73l-9.86-1.28-4.12-8.88a1 1 0 0 0-1.82 0z">
      </path>
    </svg>
  <% end %>
 <div class="review-content">
    <p><%= review.content %></p>
  </div>
</div>
 <span class="review-time">• <%= time_ago_in_words(review.created_at) %> ago</span>

app/views/products/_review_item.html.erb
<div class="flex text-yellow-500">
<button 
            type="button" 
            data-controller="reviews"
            data-action="click->reviews#toggleReviewsModal"
            data-reviews-product-id-value= "<%= product.id %>"
            >  
              <% if product.average_final_rating.present? %>
              <% full_stars = product.average_final_rating.floor %>
              <% half_star = (product.average_final_rating.round(2) % 1) >= 0.5 %>
              <% empty_stars = 5 - full_stars - (half_star ? 1 : 0) %>
              <% full_stars.times { %><span>&#9733;</span><% } %>
              <% if half_star %><span>&#9733;&#xFE0E;</span><% end %>
              <% empty_stars.times { %><span class="text-gray-300">&#9733;</span><% } %>
              <%end%>
               <svg xmlns="http://www.w3.org/2000/svg"
                fill="none"
                 viewBox="0 0 24 24"
                  stroke-width="1.5" 
                  stroke="currentColor"
                   class="size-4 text-black">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                    </svg>
              </button>
              </div>
             
                 <% if product.reviews_count > 0 %>
             
           <%= render 'shared/modal',
             modalTriggerId: "reviews_#{product.id}", # Unique ID for each product
             content: 'products/reviews_modal', 
             content_params: { product: product }
            %>

            
            <% end %>

app/views/products/_reviews.html.erb
 <div class="flex items-center mt-1">
 <div class="flex text-yellow-500">
      <button 
            type="button" 
            data-controller="reviews"
            data-action="click->reviews#toggleReviewsModal"
            data-reviews-product-id-value= "<%= product.id %>"
            >  
              <% if product.average_final_rating.present? %>
              <% full_stars = product.average_final_rating.floor %>
              <% half_star = (product.average_final_rating.round(2) % 1) >= 0.5 %>
              <% empty_stars = 5 - full_stars - (half_star ? 1 : 0) %>
              <% full_stars.times { %><span>&#9733;</span><% } %>
              <% if half_star %><span>&#9733;&#xFE0E;</span><% end %>
              <% empty_stars.times { %><span class="text-gray-300">&#9733;</span><% } %>
              <%end%>
               <svg xmlns="http://www.w3.org/2000/svg"
                fill="none"
                 viewBox="0 0 24 24"
                  stroke-width="1.5" 
                  stroke="currentColor"
                   class="size-4 text-black">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                    </svg>
              </button>
              
            </div>
            <span class="text-blue-600 text-sm ml-2"><%= number_with_delimiter(product.reviews_count) %></span>
            
            </div>
          <span class="text-black text-sm ml-2">Ships to <%= (product.country_code) %></span>
             <div class="flex items-center justify-between mt-3">
            <span><%= humanized_money_with_symbol(product.price) %></span>
          </div>
           
            <div class="items-center justify-between mt-3">
             
            </div>

           
           <div class="flex items-center justify-between mt-3">
           
             </div>
             <% if product.reviews_count > 0 %>
             
           <%= render 'shared/modal',
             modalTriggerId: "reviews_#{product.id}", # Unique ID for each product
             content: 'products/reviews_modal', 
             content_params: { product: product }
            %>

            
            <% end %>
          

app/views/products/_shipping_modal.html.erb
<div class="grid " style="width: 300px;">
    <!-- Review Stats -->
    <section aria-labelledby="delivery-stats" class="col-span-2 pt-10 pb-10">
     
    <button data-action="click->modal#toggleModal" type="button" class="relative rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
    <span class="absolute -inset-2.5"></span>
    <span class="sr-only">Close panel</span>
    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  </button>
  <span class="flex" id="product-price">Product Price&nbsp;<%= @product.price %></span>
  <div id="shipping_modal" class="modal">
  <p class="flex">Shipping Cost: <span id="shipping-cost">0</span></p> 
  <p class="flex">Total Price: <span id="total-price"><%= @product.price %></span></p> 
</div>
</section>
  </div>

app/views/products/index.html.erb
<div data-controller="filter">
  <h2 class="text-2xl font-semibold mb-4 text-gray-900"><%= @subcategory.name %></h2>

  <div class="w-full max-w-xs p-4 bg-white rounded-lg shadow-md">
    <label class="font-semibold text-gray-800">Price</label>
    <div class="flex justify-between text-sm font-medium text-gray-700">
      <span data-filter-target="minPrice">$1</span>
      <span data-filter-target="maxPrice">$180+</span>
    </div>

    <div class="relative mt-2">
      
      <input type="range" min="1" max="180" value="1"
        data-action="input->filter#updatePrice change->filter#applyFilter"
        data-filter-target="minRange"
        class="absolute w-full h-2 bg-teal-600 rounded-lg appearance-none cursor-pointer outline-none">
      
      <input type="range" min="1" max="180" value="180"
        data-action="input->filter#updatePrice change->filter#applyFilter"
        data-filter-target="maxRange"
        class="absolute w-full h-2 bg-teal-600 rounded-lg appearance-none cursor-pointer outline-none">
    </div>

    <button data-action="click->filter#applyFilter"
      class="mt-4 w-full px-4 py-2 text-teal-600 border border-teal-600 rounded-lg hover:bg-teal-600 hover:text-white transition">
      Go
    </button>
  </div>
<div id="product_list">
  <div data-filter-target="productList" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
    <% @products.each do |product| %>
    <%= link_to subcategory_product_path(product.subcategory, product) do%>
      <div class="bg-white shadow-lg rounded-lg p-4 hover:shadow-xl transition duration-300">
        <div class="relative">
          <% if product.images.attached? %>
            <% image = product.images.first %>
            <%= image_tag image, class: "w-full h-48 object-cover rounded" %>
          <% end %>
        </div>
        
        <div class="mt-4">
          <span class="cursor-pointer text-gray-900 font-medium text-lg hover:text-blue-600">
            <%= product.headline %>
          </span>
           <% end %>
          <!----------render reviews in index page of products--------------->
            <%= render :partial => 'products/reviews', :locals => {:product => product,:style=>@style}%>
          </div>
      </div>
      <% end %>
   
  </div>
  </div>
  </div>